{{- if .Values.fhirResourceServer.enabled -}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: fhir-resource-server
  labels: 
    app.kubernetes.io/component: fhirResourceServer
    app: fhir-resource-server
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.fhirResourceServer.replicaCount }}
  {{- if .Values.fhirResourceServer.updateStrategy }}
  strategy: {{- toYaml .Values.fhirResourceServer.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: 
      app: fhir-resource-server
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: fhir-resource-server
        app.kubernetes.io/component: fhirResourceServer
        {{- if .Values.fhirResourceServer.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.fhirResourceServer.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.fhirResourceServer.nodeSelector "context" $) | nindent 8 }}
      {{- end }}      
      {{- if .Values.fhirResourceServer.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.fhirResourceServer.priorityClassName }}
      priorityClassName: {{ .Values.fhirResourceServer.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.fhirResourceServer.schedulerName }}
      schedulerName: {{ .Values.fhirResourceServer.schedulerName | quote }}
      {{- end }}
      {{- if .Values.fhirResourceServer.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.fhirResourceServer.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.fhirResourceServer.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: fhir-resource-server
          image: {{ template "catalogue.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.fhirResourceServer.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.fhirResourceServer.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.fhirResourceServer.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.fhirResourceServer.args }}
          args: [{{- range $index, $str := .Values.fhirResourceServer.args }}{{ if eq $index 0 }}{{- . | quote }} {{ else }},{{  . | quote }} {{- end }}{{- end }}]
          {{- end }}
          
          
          {{- if .Values.fhirResourceServer.resources }}
          resources: {{- toYaml .Values.fhirResourceServer.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.fhirResourceServer.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.fhirResourceServer.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.fhirResourceServer.sidecars "context" $) | nindent 8 }}
        {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
            - name: hazelcast
              containerPort: {{ .Values.containerPorts.hazelcast }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.containerPorts.prometheus }}
              protocol: TCP
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.fhirResourceServer.livenessProbe.enabled }}
          livenessProbe:
             httpGet:
               path: {{ .Values.fhirResourceServer.livenessProbe.path }}
               port: 9000
             initialDelaySeconds: {{ .Values.fhirResourceServer.livenessProbe.initialDelaySeconds }}
             periodSeconds: {{ .Values.fhirResourceServer.livenessProbe.periodSeconds }}
             timeoutSeconds: {{ .Values.fhirResourceServer.livenessProbe.timeoutSeconds }}
          
          {{- else if .Values.fhirResourceServer.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.fhirResourceServer.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.fhirResourceServer.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.fhirResourceServer.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.fhirResourceServer.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.fhirResourceServer.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.fhirResourceServer.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.fhirResourceServer.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            {{- if .Values.fhirResourceServer.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.fhirResourceServer.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.extraEnvVarsSecret "context" $) }}
            {{- end }}
            {{- if .Values.fhirResourceServer.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
      {{- if .Values.serviceAccount.create }}    
      serviceAccountName: {{ template "catalogue.serviceAccountName" . }}
      {{- end }}
      {{- include "catalogue.imagePullSecrets" . | nindent 6 }}
      
      {{- if .Values.fhirResourceServer.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.fhirResourceServer.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.fhirResourceServer.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        {{- if .Values.fhirResourceServer.podAffinityPreset}}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.fhirResourceServer.podAffinityPreset "component" "fhirResourceServer" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.fhirResourceServer.podAntiAffinityPreset }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "component" "fhirResourceServer" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.fhirResourceServer.nodeAffinityPreset.type }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.fhirResourceServer.nodeAffinityPreset.type "key" .Values.fhirResourceServer.nodeAffinityPreset.key "values" .Values.catalogue.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.fhirResourceServer.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.fhirResourceServer.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
