{{- if and .Values.fhirResourceServer.enabled .Values.fhirResourceServer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fhir-resource-server
  labels:
    app: fhir-resource-server
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: fhir-resource-server
  minReplicas: {{ .Values.fhirResourceServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fhirResourceServer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.fhirResourceServer.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fhirResourceServer.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.fhirResourceServer.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.fhirResourceServer.autoscaling.targetMemory  }}
    {{- end }}
{{- end }}
